# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Eric Pei | Home
description: >- # this means to ignore newlines until "baseurl:"
  My personal site

baseurl: "" # for testing locally
# baseurl: "/blog" # the subpath of the site
url: "https://crackersamdjam.github.io" # the base hostname & protocol for the site

# not sure if I need to change those, but right now my custom domain is working fine
# right now, crackersamdjam.github.io/blog -> new.ericpei.ca

og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/crackersamdjam
    - name: GitHub
      link: http://github.com/crackersamdjam

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
